,dep,version,filepath,bloated,cve,affected versions,advisory
0,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
1,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
2,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
3,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
4,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
5,numpy,>=1.9.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
6,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
7,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
8,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
9,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
10,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
11,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
12,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
13,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
14,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
15,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
16,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
17,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
18,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
19,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
20,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
21,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
22,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
23,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
24,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
25,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
26,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
27,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
28,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
29,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
30,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
31,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
32,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
33,opencv-python,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
34,six,>=1.9.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,no one,no one,no one
35,requests,>=2.22.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2015-2296,">=2.1,<=2.5.3",The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.
36,requests,>=2.22.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/setup.py,False,CVE-2023-32681,">=2.3.0,<2.31.0","Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use 'rebuild_proxies' to reattach the 'Proxy-Authorization' header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the 'Proxy-Authorization' header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.

"
37,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
38,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
39,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
40,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
41,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
42,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
43,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
44,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
45,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
46,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
47,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
48,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
49,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
50,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
51,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
52,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
53,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
54,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
55,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
56,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
57,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
58,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
59,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
60,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
61,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
62,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
63,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
64,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
65,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
66,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
67,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
68,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
69,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
70,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
71,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
72,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
73,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
74,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
75,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,PVE-2022-52255,<0.24.2,"Scikit-learn 0.24.2 includes a fix for a ReDoS vulnerability.
https://github.com/scikit-learn/scikit-learn/issues/19522"
76,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2020-13092,">=0,<0.23.1","** DISPUTED ** scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
77,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,CVE-2020-28975,">=0,<0.24.dev0","** DISPUTED ** svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array. NOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute."
78,sphinxcontrib-apidoc,==0.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,no one,no one,no one
79,six,>=1.9.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/videoflow/docs/source/requirements.txt,False,no one,no one,no one
