,dep,version,filepath,bloated,cve,affected versions,advisory
0,emoji,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,no one,no one,no one
1,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
2,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
3,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
4,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
5,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
6,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
7,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2014-1859,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1859: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/pull/4262"
8,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2014-1858,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1858: __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
9,protobuf,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2021-22570,<3.15.0,"Protobuf 3.15.0 includes a fix for CVE-2021-22570: Nullptr dereference when a null char is present in a proto symbol. The symbol is parsed incorrectly, leading to an unchecked call into the proto file's name during generation of the resulting error message. Since the symbol is incorrectly parsed, the file is nullptr."
10,protobuf,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
11,protobuf,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2015-5237,<3.4.0,"Protobuf 3.4.0 includes a fix for CVE-2015-5237: Integer overflow in serialization.
https://github.com/protocolbuffers/protobuf/issues/760"
12,requests,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2014-1830,<2.3.0,Requests before 2.3.0 exposes Authorization or Proxy-Authorization headers on redirect. This fixes CVE-2014-1830.
13,requests,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2014-1829,<2.3.0,Requests before 2.3.0 exposes Authorization or Proxy-Authorization headers on redirect. See: CVE-2014-1829.
14,requests,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2018-18074,<=2.19.1,"Requests before 2.20.0 sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network."
15,requests,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2015-2296,">=2.1,<=2.5.3",The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.
16,requests,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2023-32681,">=2.3.0,<2.31.0","Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use 'rebuild_proxies' to reattach the 'Proxy-Authorization' header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the 'Proxy-Authorization' header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.

"
17,six,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,no one,no one,no one
18,torch,>=1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
19,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
20,check-manifest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,no one,no one,no one
21,coverage,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,no one,no one,no one
22,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,no one,no one,no one
23,transformers,>=3.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,CVE-2022-1941,<4.23.0,Transformers 4.23.0 updates its dependency 'protobuf' requirement to '<=3.20.2' to include a security fix.
24,transformers,>=3.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,PVE-2022-51450,<4.23.0,"Transformers 4.23.0 includes a fix for a link vulnerable to repojacking.
https://github.com/huggingface/transformers/commit/ce2620194b4a8f070cd29504d34a79758affdf95"
25,transformers,>=3.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/stanza/setup.py,False,PVE-2021-40187,<4.5.0,Transformers 4.5.0 includes various vulnerability fixes.
